server:
  port: 2024
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: HikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yukio?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      host: localhost
      port: 6379
      database: 2
jwt:
  secret: U2FsdGVkX18epMj+KK0TtMyZJzvr45zahWHKpl4+kSg=
  access-token-ttl: 3600000 #accessToken过期时间，单位毫秒，3600000毫秒为1小时
  refresh-token-ttl: 604800000 #refreshToken过期时间，单位毫秒，604800000毫秒为7天
  auto-refresh-ttl: 120000 #凭证剩余时间小于该值时自动刷新，单位毫秒，1200000为二十分钟