import {
    // component
    NButton,
    NCard,
    NCheckbox,
    NCheckboxGroup,
    NDataTable,
    NDivider,
    NDropdown,
    NFlex,
    NForm,
    NFormItem,
    NH2,
    NIcon,
    NInput,
    NLayout,
    NLayoutContent,
    NLayoutFooter,
    NLayoutHeader,
    NLayoutSider,
    NModal,
    NPopconfirm,
    NPopover,
    NPopselect,
    NRadio,
    NRadioButton,
    NRadioGroup,
    NSelect,
    NSpace,
    NSpin,
    NSplit,
    NSwitch,
    NTooltip,
    // create naive ui
    create,
    NAlert,
} from 'naive-ui'

const naive = create({
    components: [
        NButton,
        NLayout,
        NLayoutHeader,
        NLayoutContent,
        NLayoutSider,
        NLayoutFooter,
        NH2,
        NCard,
        NInput,
        NRadioGroup,
        NRadio,
        NRadioButton,
        NDataTable,
        NModal,
        NTooltip,
        NForm,
        NFormItem,
        NSelect,
        NDropdown,
        NSpace,
        NFlex,
        NIcon,
        NPopselect,
        NSpin,
        NDivider,
        NCheckbox,
        NCheckboxGroup,
        NSwitch,
        NSplit,
        NPopover,
        NPopconfirm,
        NDivider,
        NAlert,
    ],
})

export default naive
